### ISSUE TITLE
fron-end code 

### ISSUE THREAD

**Issue by MYahya1980** [Aliyansayz/Screening-Assistance-Project#1]
import streamlit as st

# Title of the app
st.title('Smart Tourist')

# Initialize session state for chat history if it doesn't exist
if 'chat_history' not in st.session_state:
    st.session_state.chat_history = []

# Custom CSS for user message, reply message, and send button
st.markdown("""
    <style>
    .user-message {
        text-align: left;
        margin: 5px;
        padding: 5px;
        background-color: #f0f0f0; /* Light grey background for user message */
        border-radius: 5px;
    }
    .reply-message {
        text-align: right;
        margin: 5px;
        padding: 5px;
        background-color: #d0d0d0; /* Slightly darker grey for reply message */
        border-radius: 5px;
    }
    .send-button {
        width: 36px;
        height: 36px;
        padding: 0;
        border-radius: 18px;
        line-height: 0;
        display: inline-block;
        text-align: center;
        vertical-align: middle;
        margin-top: 30px;
    }
    .stTextInput > div > div > input {
        padding-right: 40px;
    }
    </style>
    """, unsafe_allow_html=True)

# Function to handle text input and send button
def handle_input():
    user_input = st.session_state.user_input
    if user_input:
        # Append user query and reply to chat history
        st.session_state.chat_history.append(("user", user_input))
        st.session_state.chat_history.append(("reply", "Answer here..."))
        # Clear the input box
        st.session_state.user_input = ""

# Display chat history
chat_container = st.empty()
with chat_container.container():
    for message_type, message in st.session_state.chat_history:
        if message_type == "user":
            st.markdown(f'<div class="user-message">{message}</div>', unsafe_allow_html=True)
        elif message_type == "reply":
            st.markdown(f'<div class="reply-message">{message}</div>', unsafe_allow_html=True)

# Layout for input and send button
col1, col2 = st.columns([5, 1], gap="small")
with col1:
    user_input = st.text_input("Ask me anything about tourism!",
                               key="user_input",
                               value="",
                               on_change=handle_input,
                               args=())
with col2:
    st.markdown('<button class="send-button">&#x1F815;</button>', unsafe_allow_html=True)

**Comment by Aliyansayz** [comment]
def handle_input():
user_input = st.session_state.user_input
if user_input:
answer = get_answer(query = input, qa_chain= qa_chain)
# Append user query and reply to chat history
st.session_state.chat_history.append(("user", user_input))

st.session_state.chat_history.append(("reply", f"Ans: {answer}" ))

**Comment by Aliyansayz** [comment]
Ek chota saa Kaam tha : basss yeh kch questions hen inn ko front end m daal doo aur jis button pe click krna hoo woh input k andr aa jae. 

"Safety contact Emergency Services Lost Items" : [ "What are the safety precautions I should take during Hajj?",
"Who should I contact in case of emergencies?",
"What emergency response services are available in Mecca and Medina?",
"What are the procedures for lost and found items and missing pilgrims?" ] ,

"Hotel Room Service book Hajj" : [ "What types of accommodation are available during Hajj?" , 
"How can I book a hotel or other suitable lodging?", 
"What amenities and services are typically provided by hotels during Hajj?" , 
"What are the regulations and protocols for hotel check-in and check-out during Hajj?"
 ] ,

" Waste Trash Clean" : [ "How can I contribute to a clean and sanitary environment during Hajj?",
"Where can I dispose of waste properly?",
"What are the environmental regulations for pilgrims?", 
"Are there initiatives to promote sustainable practices during Hajj?" ] , 

"Health Medical vaccine " : 
[ "What common health risks are associated with Hajj?" ,
"What vaccinations are required or recommended for pilgrims?",
"Where can I find medical assistance in Mecca and Medina?",
"Will my medicare cover any medical expenses incurred during Hajj?" ] , 

"Transportation" : [ "How can I get around Mecca and Medina during Hajj?" ,
"Is public transportation available?",
"Are there private transportation options?",
"What are the regulations for car rentals and hiring taxis?" ],

    "Food Water Diet" : [ "What kind of food will be available?",
"Do I need to bring my own food and water?", 
"Are there dietary restrictions in Mecca and Medina?", 
"Where can I find safe and hygienic drinking water?" ] ,

**Comment by Aliyansayz** [comment]
Baqi backend ka me yeh kr loon ga : 

___________________________________________________________________________


def create_docs(directory, unique_id):

  pdfloader = PDFReader()
  user_file_list = os.listdir(directory)
  docs = []

  for filename in user_file_list:
    
      filepath = os.path.join(directory, filename)
      ext = filename.split(".")[-1]

      # Use PDFLoader for .pdf files
      if ext == "pdf":
          
          doc = pdfloader.load_data(file=Path(f'{filepath}'))
          # loader = PyPDFLoader(filepath)
          return doc
      else:
          continue
      docs.append(Document( page_content= doc[0].page_content , metadata={"name": f"{filename}" , "unique_id":unique_id } ) )

  return docs
________________________________________________________________________________
def define_qa(): 
       
     model_name = "text-davinci-003"
     # model_name = "gpt-3.5-turbo"
     # model_name = "gpt-4"
     llm = OpenAI(model_name=model_name)

     qa_chain =load_qa_chain(llm, chain_type="stuff")
    
     return qa_chain 
________________________________________________________________________________
def get_answer(query, qa_chain, relevant_docs ):
    
    qa =  load_qa_chain(llm, chain_type="stuff")
    
    result = qa(query)
    answer =  qa_chain.run(input_documents=relevant_docs,
     question=query)
    
    return answer
________________________________________________________________________________

**Comment by MYahya1980** [comment]
**Buttons ka code ha ya**


# Function to update the input field with button value
def update_input(value):
    st.session_state.button_input = value

# Buttons for various services
st.markdown("### Services")
btn1, btn2, btn3, btn4, btn5, btn6 = st.columns(6)
if btn1.button("Emergency Services"):
    update_input("What are the safety precautions I should take during Hajj?")
if btn2.button("Hotel Services"):
    update_input("What types of accommodation are available during Hajj?")
if btn3.button("Waste Trash Clean"):
    update_input("How can I contribute to a clean and sanitary environment during Hajj?")
if btn4.button("Health Medical Vaccine"):
    update_input("What common health risks are associated with Hajj?")
if btn5.button("Transportation"):
    update_input("How can I get around Mecca and Medina during Hajj?")
if btn6.button("Food Water Diet"):
    update_input("What kind of food will be available?")
